version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm test running"
      - run: npm install
      - run: npm test
  coverage:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "coverage here saying hello - dependency of test"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - coverage
      - test:
        requires:
          - coverage
